
import { Platform, StatusBar, StyleSheet } from "react-native";

export const HeaderStyles = (colorScheme: "light" | "dark") =>
  StyleSheet.create({
  container: { width: "100%" },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "100%",
    paddingHorizontal: 8,
    paddingVertical:12,
    // marginTop: Platform.OS === "android" ? 10 : 60,
    zIndex: 100,
    backgroundColor: "#fff",
  },
  headerBottomBorder: {
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0, 0, 0, 0.1)",
    paddingBottom: 10,
  },

  leftSection: {
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
    minWidth: 40,
  },
  backButton: { padding: 4 },
  title: { fontSize: 20, fontWeight: "bold" },
  menuButton: { padding: 4 },
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.3)",
  },
  sidebarLight: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    backgroundColor: "#fff",
    paddingHorizontal: 16,
    paddingTop: Platform.OS === "android" ? StatusBar.currentHeight || 16 : 40,
    justifyContent: "space-between",
    shadowColor: "#000",
    shadowOffset: { width: 2, height: 0 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 6,
  },
  sidebarItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
  },
  icon: { marginRight: 12 },
  menuList: { flexGrow: 1 },
  bottomSection: {
    backgroundColor: "#fff",
    borderTopWidth: 1,
    borderTopColor: "#E0E0E0",
    paddingTop: 8,
    paddingBottom: 24,
  },
  bottomButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 12,
    backgroundColor: "#fff",
  },
  settingsMenu: { paddingLeft: 28, paddingBottom: 8 },
  subItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 8,
    gap: 8,
  },
  subItemText: { fontSize: 15, color: "#333" },
  badge: {
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 6,
    marginLeft: 8,
  },
  badgeText: { fontSize: 10, fontWeight: "700", color: "red", opacity: 0.25 },
  menuRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 14,
    gap: 12,
  },
  menuText: { fontSize: 16, color: "#292D32" },
  customerBottomSection: {
    borderTopWidth: 1,
    borderTopColor: "#E5E5E5",
    paddingTop: 24,
    paddingBottom: 20,
  },
  vendorButton: {
    marginTop: 30,
    backgroundColor: "#000",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    borderRadius: 50,
  },
  vendorButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "800",
    marginLeft: 8,
  },
});